### ISSUE TITLE
Should this be used over googlemusic-xbmc?

### ISSUE THREAD

**Issue by bryanwillis** [foreverguest/repository.foreverguest#1]
From a few [blogs](https://seo-michael.co.uk/how-to-add-google-play-music-to-xbmc-kodi/) I've seen online these appear to both be for google music, but [googlemusic-xbmc](https://github.com/foreverguest/googlemusic-xbmc) looks like it hasn't been updated in a couple years. Should this one be used over that one or are they separate in functionality? Thanks!

**Comment by foreverguest** [comment]
Yeah that fork is not updated, you can use vially's https://github.com/vially/googlemusic-xbmc, for updated source.
