### ISSUE TITLE
script.module.decorator missing in LibreELEC

### ISSUE THREAD

**Issue by fermulator** [foreverguest/repository.foreverguest#11]
Hello,

Have enjoyed your plugin for Google Music on other full-fledged Linux systems (Ubuntu).
This week on a different device got LibreELEC running which latest stable is Kodi Krypton.
```
~ # cat /etc/issue
##############################################
#                  LibreELEC                 #
#            https://libreelec.tv            #
##############################################

LibreELEC (official): 8.2.5 (Generic.x86_64)
```

Followed typical instructions to get this addon into that system
(i.e. https://www.kodireviews.com/google-music-addon/)

Upon attemping to install addon from foreverguest repo, error about dependency on `script.module.decorator`.

Full logs:
```
22:20:16.382 T:140513283237632   ERROR: CAddonInstallJob[plugin.audio.googlemusic.exp]: The dependency on script.module.decorator version 3.4.0 could not be satisfied.
```

This addon is definitely not present by default
```
~/.kodi/addons # ls -al | grep decorator
(NO RESULT)
```

On my OTHER system, it is definitely present
```
~/.kodi/addons/script.module.decorator$ ls -al
total 44
drwxr-xr-x   3 multimedia multimedia  4096 Jan  1  2017 .
drwxr-xr-x 222 multimedia multimedia 12288 Dec  2 00:00 ..
-rw-rw-r--   1 multimedia multimedia   690 Jan  1  2017 addon.xml
-rw-rw-r--   1 multimedia multimedia    40 Jan  1  2017 changelog.txt
-rw-rw-r--   1 multimedia multimedia  7237 Jan  1  2017 icon.png
drwxr-xr-x   2 multimedia multimedia  4096 Jan  1  2017 lib
-rw-rw-r--   1 multimedia multimedia  1311 Jan  1  2017 LICENSE.txt
-rw-rw-r--   1 multimedia multimedia    56 Jan  1  2017 README.md

~/.kodi/addons/script.module.decorator$ grep version addon.xml 
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
       version="3.4.0"
    <import addon="xbmc.python" version="2.1.0"/>

```

Thoughts? Googling around for this exact error yielded nearly no fruit.
I _could_ attempt to scp the files from the other system over to hack/workaround; but I suspect we have a dependency issue here for minimal Kodi installations such as LibreELEC based.

**Comment by fermulator** [comment]
Also of note, if I search specifically for this addon, it DOES link us to:
https://mirrors.kodi.tv/addons/krypton/script.module.decorator/
, but that link is dead

(wondering if this is a dead addon or what the state is)

**Comment by fermulator** [comment]
I tried the workaround. Shoving that addon into the system did not help ;/ hm.

**Comment by foreverguest** [comment]
It seems to be removed from the official repository. I'll add it to my repository soon.

**Comment by foreverguest** [comment]
Module added.

**Comment by fermulator** [comment]
Seeing it in https://github.com/foreverguest/repository.foreverguest/commit/69fca71a9f7bb4009b6f6cd00207acd2adecdc5f

**Comment by fermulator** [comment]
(do you need to build/deliver before its public/avail?)

**Comment by foreverguest** [comment]
It should be available. Tested with success here.

**Comment by fermulator** [comment]
VERIFIED FIX! (worked today)
-
(my 2 days ago post I guess it had not yet somehow been refreshed, or the Kodi system was pull from a cache not sure)

**Comment by fermulator** [comment]
(er, i dunno how to "mark as fixed", for some reason "CLOSE" appears to indicate "not fixed")
