### ISSUE TITLE
Radio Free

### ISSUE THREAD

**Issue by NonaSuomy** [foreverguest/repository.foreverguest#2]
Hi foreverguest,

Were you able to get this working?

http://forum.kodi.tv/showthread.php?tid=200640&pid=2275152#pid2275152

**Comment by foreverguest** [comment]
Yeah, I have it working, but as it is a different path than was used in subscriber radio, I have to adapt the addon code to detect and work for each case.
I hope I can finish that work this week.

**Comment by foreverguest** [comment]
Please test version below:
https://app.box.com/s/rsoenjmj3uub12v9g5mpxor99xn7lwn9

**Comment by NonaSuomy** [comment]
Great work!

You just made Kodi decent for good new radio streaming again!

So far working great!

Anyway to get a search option "Indie Apartment Party" etc, 

A way to save your favorite stations

Album Art change on the background instead of just the orange headphones. On the Google Music page you can click the album art playing. Which gives you two options that pop-out for Full Screen (Album Art & Particle Effect). 

Album Art does a slideshow of the cover panning around, 
Probably just use our internal slideshow feature for that.

Particle Effect has two smokey dots on the screen that move around to the beat.
(Be nice if you could use the album art slideshow with the viz in the foreground, I noticed that shadertoy viz overlays the orange headphones background.)

After that it's basically complete.

If not, no biggy, more than happy with what you did so far!

**Comment by NonaSuomy** [comment]
If you hit skip a few times it errors out, I don't normally use the skip as I treat it like radio so this is not really an issue for me, I noticed on the website there is a pay limit for skipping which requires an unlimited account "You're out of skips. Get on-demand and offline access to millions of songs for $9.99 per month. SUBSCRIBE"

Maybe add an error catch for this so it doesn't look like the script is having an issue, On the official website the first few skips some times gives you a commercial then a count down of how many more times you can press skip. Maybe use the notification popup in Kodi to show this happening so the free users know what's going on and not an issue with the plugin. As after all the skips are done it seems that it will no longer go to the next song naturally until you click another station. Then it resets the skip count.

When you press next in kodi it actually stops playing where the online player just keeps playing the last song not sure how you would stop the user from killing the last song allowed to skip, so it goes back to naturally playing the songs without skipping allowed.

The some times commercial might be an issue as well.

Looks like the official site gives you 4 skips until it warns you
"2 skips left. GET MORE"
"1 skip left. GET MORE"
"You're out of skips. Get on-demand and offline access to millions of songs for $9.99 per month. SUBSCRIBE"

**Comment by foreverguest** [comment]
Background art will be improved, already working on that.
Do you think we should start the slideshow whenever we start playing the radio?
I have noticed Google returned a skip limit when querying the radio. I can show a notification on radio start.

**Comment by foreverguest** [comment]
https://app.box.com/s/bf8447r2c5574gwjtiaj469awatpebus

**Comment by NonaSuomy** [comment]
Great work once again!
Is there a way to get it to change the background to the album art as it is always changing per song, where the background now is only the "station" background that is always the same?

Search and favourites would be nice as well if plausible.
