### ISSUE TITLE
Please update your gmusicapi

### ISSUE THREAD

**Issue by philBrown** [foreverguest/repository.foreverguest#4]
Hi

Your fork / copy of gmusicapi is quite a ways behind Simon's (https://github.com/simon-weber/gmusicapi) and I believe it may be contributing to this other issue ~ https://github.com/vially/googlemusic-xbmc/issues/66#issuecomment-230728864

Any chance you could update it and release a new version?

Cheers

**Comment by foreverguest** [comment]
It is still working for me, could you try 'Clear cookie' in addon settings?

**Comment by philBrown** [comment]
Already tried that.

**Comment by foreverguest** [comment]
Try removing file .kodi/userdata/addon_data/plugin.audio.googlemusic.exp/settings.xml

**Comment by philBrown** [comment]
That fixed it, thanks!
