### ISSUE TITLE
GoogleMusicEXP - Can't login from 1.10.6

### ISSUE THREAD

**Issue by philBrown** [foreverguest/repository.foreverguest#6]
Since the addon updated to 1.10.6, I get login failures.

    NOTICE: [GoogleMusicEXP-1.10.6]  ARGV: ['plugin://plugin.audio.googlemusic.exp/', '3', '']
    NOTICE: [GoogleMusicEXP-1.10.6] Checking init data
    NOTICE: [GoogleMusicEXP-1.10.6] Trying to fetch the device_id
    NOTICE: [GoogleMusicEXP-1.10.6] Logging in
    NOTICE: [GoogleMusicEXP-1.10.6] Login in with device_id failed, trying with MAC
    NOTICE: [GoogleMusicEXP-1.10.6] Login failed
    ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
         - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
        Error Type: <type 'exceptions.TypeError'>
        Error Contents: exceptions must be old-style classes or derived from BaseException, not NoneType
        Traceback (most recent call last):
          File "/storage/.kodi/addons/plugin.audio.googlemusic.exp/default.py", line 21, in <module>
            utils.checkInit()
          File "/storage/.kodi/addons/plugin.audio.googlemusic.exp/utils.py", line 105, in checkInit
            login.initDevice()
          File "/storage/.kodi/addons/plugin.audio.googlemusic.exp/GoogleMusicLogin.py", line 53, in initDevice
            self.login()
          File "/storage/.kodi/addons/plugin.audio.googlemusic.exp/GoogleMusicLogin.py", line 105, in login
            raise
        TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
        -->End of Python script error report<--
    ERROR: GetDirectory - Error getting plugin://plugin.audio.googlemusic.exp/
    ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.googlemusic.exp/) failed

I'm using 2-step authentication and have generated an app password. I've also tried completely removing the addon and re-installing it without any luck.

This is running on a RPi / OpenElec 6.0.3

**Comment by foreverguest** [comment]
Your user/pass combination is failing, have you tried the same combination on another device or application?

**Comment by philBrown** [comment]
Thanks, it seems you may be right though I'm not sure what changed. I hadn't changed any settings nor revoked the app password (wish Google would let you see them).

I checked with another app that doesn't support 2FA and it failed. Generated a new app password and that worked. Will check with the addon shortly.
