### ISSUE TITLE
Cannot start up due to "Invalid Credentials" Error in Log

### ISSUE THREAD

**Issue by tcv12** [foreverguest/repository.foreverguest#8]
Every time I try to start it up, it gives me an immediate error, I have checked the log and apparently I have incorrect credentials. My login details are not incorrect as I have triple checked the login email and password.

**Comment by foreverguest** [comment]
Do you use 2-step authentication? If yes you need to create an app specific password.

**Comment by tcv12** [comment]
I've done that and have tried 3 times and still nothing. Would it be something to do with me running a beta version of Kodi 17?

**Comment by foreverguest** [comment]
It should work, I am using it with Kodi 17 beta6.
But try with stable version and check if something changes.
Also you can upload your log to pastebin so I can look for any clues about your problem.
